kind = "web"
previewPath = "/"
title = "JAM CRITTY"
version = "1.0.0"
id = "artifacts/jam-critty"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22711

[services.development]
run = "pnpm --filter @workspace/jam-critty run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/jam-critty", "run", "build" ]
publicDir = "artifacts/jam-critty/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22711"
BASE_PATH = "/"
